#!/bin/sh
# Container entrypoint: nginx serves the SPA and proxies /api and /ws to the
# node process started here. PID 1 is tini (see the Dockerfile), so this script
# is PID 2 and node becomes a child that tini reaps.
set -eu

mkdir -p "${UPLOAD_DIR:-/data/uploads}"

export UPLOAD_DIR="${UPLOAD_DIR:-/data/uploads}"

# The API boots with `import 'dotenv/config'`, which reads /app/.env. Load the
# same file here as well so anything the SPA needs is available when the runtime
# config is written below, and so the warning further down is accurate. Values
# already set in the environment win, because dotenv does not override them.
if [ -r /app/.env ]; then
  set -a
  # shellcheck disable=SC1091
  . /app/.env
  set +a
  echo "Loaded /app/.env"
fi

# The frontend bundle is built once, but the InsForge coordinates and the
# websocket origin differ per environment. Generate runtime-config.js from the
# environment so one image runs in dev, staging and production.
write_runtime_config() {
  escape() {
    printf '%s' "$1" | sed -e 's/\\/\\\\/g' -e 's/"/\\"/g'
  }
  cat > /usr/share/nginx/html/runtime-config.js <<EOF
// Generated by docker/entrypoint.sh at container start. Do not edit.
window.__RUNTIME_CONFIG__ = {
  VITE_INSFORGE_URL: "$(escape "${INSFORGE_URL:-}")",
  VITE_INSFORGE_ANON_KEY: "$(escape "${INSFORGE_ANON_KEY:-}")",
  VITE_WS_URL: "$(escape "${VITE_WS_URL:-}")"
};
EOF
}
write_runtime_config

# Fail fast with a clear message instead of a blank page in the browser: the
# SPA cannot create its InsForge client without these.
if [ -z "${INSFORGE_URL:-}" ] || [ -z "${INSFORGE_ANON_KEY:-}" ]; then
  echo "warning: INSFORGE_URL / INSFORGE_ANON_KEY are not set." >&2
  echo "         The UI will not be able to reach the InsForge backend." >&2
fi

# Validate the generated config before nginx starts serving it.
nginx -t

# Daemon mode: node replaces this script as the foreground process, and if it
# exits the container exits so the orchestrator can restart the pod.
nginx
exec node backend/dist/index.js
